name: Bundle Deploy Reference

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          echo "pip install databricks-cli"

      - name: Authenticate
        run: |
          echo "Use GitHub Secrets"

      - name: Bundle Validate
        run: |
          echo "databricks bundle validate"

      - name: Bundle Deploy
        run: |
          echo "databricks bundle deploy --target dev"